export const industrialExperience = [
    "Accounting Finance",
    "AeroSpace Defense",
    "Agriculture",
    "Architecture",
    "Automotive",
    "Banking and Financial Services",
    "Biotechnology",
    "BlockChain",
    "Business Consulting",
    "Computer Hardware",
    "Computer Software & Services",
    "Construction",
    "Content Creation",
    "Digital Marketing",
    "E-commerce",
    "Education",
    "Energy",
    "Government",
    "HealthCare",
    "Hospitality",
    "Insurance",
    "Interior Design",
    "Legal Services",
    "Management Consulting",
    "Manufacturing",
    "Non-profit",
    "Publuc Relations (PR)",
    "Real Estate",
    "Technology and IT Services",
    "Telecommunications",
    "Tourism"
]