export const location = [
  "Angola",
  "Benin Republic",
  "Canada",
  "Cote D'Ivoire",
  "Eygpt",
  "Eswatini",
  "Ethiopia",
  "Ghana",
  "Kenya",
  "Morocco",
  "Nigeria",
  "Outside Africa",
  "Rwanda",
  "South Africa",
  "Tanzania",
  "Togo",
  "Uganda",
  "Zambia",
];
