export const skill = [
    "Agile Methodologies",
    "Android Development (Java/Kotlin)",
    "API Analytics",
    "API Documentation",
    "API Gateway Design",
    "API Governance",
    "API Integration",
    "API Proxies",
    "API Security",
    "API Testing",
    "API Versioning",
    "App Store Deployment",
    "Application Deployment",
    "Authentication and Authorization",
    "Automated Testing (Selenium, Cypress)",
    "Automation Tools (Selenium, QTP)",
    "Azure SQL Database",
    "Backend Technologies",
    "Backlog Management",
    "Backup and Recovery",
    "Big Data Technologies (Hadoop, Spark)",
    "Bug Tracking (JIRA, Bugzilla)",
    "CI/CD PipelinesCloud Architecture (AWS, Azure, GCP)",
    "Cloud Data Services (AWS Redshift, Google BigQuery)",
    "Cloud Platforms (AWS, Azure, GCP)",
    "Cloud Services (AWS, Azure)",
    "Code Generation",
    "Configuration Management (Ansible, Chef, Puppet)",
    "Conflict Resolution",
    "Containerization (Docker, Kubernetes)",
    "Containerization (Docker)",
    "Continuous Integration/Continuous Deployment (CI/CD)",
    "Cross-Platform Development (Flutter, React Native)",
    "CSS Preprocessors (Sass/Less)",
    "Customer Support",
    "Data Modeling",
    "Data Pipeline Orchestration (Apache Airflow)",
    "Data Quality Management",
    "Data SecurityData Warehousing",
    "Database Design",
    "Database Management (SQL/NoSQL)",
    "Defect Reporting",
    "Design Systems",
    "DevOps Basics",
    "Enterprise Architecture",
    "ETL ProcessesFigma/Sketch/Adobe XD",
    "Financial Forecasting",
    "Frontend Technologies",
    "Frontend Testing",
    "Functional Testing",
    "High Availability",
    "HTML/CSSIncident Management",
    "Information Architecture",
    "Infrastructure as Code (Terraform, CloudFormation)",
    "Integration Patterns",
    "Interaction Design",
    "iOS Development (Swift/Objective-C)",
    "ITIL Processes",
    "JavaScript/TypeScript",
    "JIRA/Confluence",
    "JSON/YAMLKPI/OKR Setting",
    "Manual Testing",
    "Market Research",
    "Microservices",
    "Microservices Architecture",
    "Mobile Testing",
    "Mobile UI/UX Design",
    "Mocking Services",
    "Monitoring and Logging (Prometheus, Grafana)",
    "Non-Functional Testing",
    "OAuth 2.0",
    "OpenAPI Specification (OAS)",
    "Performance Optimization",
    "Performance Testing",
    "Performance Tuning",
    "PostgreSQL Administration",
    "Product Lifecycle Management",
    "React/Vue/Angular",
    "Responsive Design",
    "RESTful API Design",
    "RESTful API Development",
    "Risk Management",
    "Roadmap Planning",
    "Scalability Planning",
    "Scripting (Python, Bash)",
    "Scripting Languages (Python, Bash)",
    "Scrum Framework",
    "Security Architecture",
    "Security Best Practices",
    "Server-side Languages (Java, Python, Node.js)",
    "Serverless Architecture",
    "SOAP API",
    "Sprint Planning",
    "Sprint Retrospective",
    "SQL Query Optimization",
    "SQL/NoSQL Databases",
    "Stakeholder Management",
    "System Architecture Design",
    "System Monitoring",
    "Technology Evaluation",
    "Test Automation Frameworks",
    "Test Case Design",
    "Test Case Development",
    "Test Data Management",
    "Test Planning and Strategy",
    "Testing Frameworks",
    "Troubleshooting and Debugging",
    "Usability Testing",
    "User Acceptance Testing (UAT)",
    "User Research",
    "User Story Mapping",
    "Version Control (Git)",
    "Visual Design",
    "Webpack/Babel",
    "Wireframing and Prototyping",
  ];